"""Make embedding nullable

Revision ID: 5fcde2f1df52
Revises: 8ea8e0e68351
Create Date: 2025-09-16 15:06:00.548481

"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5fcde2f1df52"
down_revision: str | Sequence[str] | None = "8ea8e0e68351"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True
        ),
    )
    op.drop_index(
        op.f("ix_messages_embedding_vector_cosine"),
        table_name="messages",
        postgresql_ops={"embedding_vector": "vector_cosine_ops"},
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.create_index(
        "ix_messages_embedding_vector_cosine",
        "messages",
        ["embedding"],
        unique=False,
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"embedding_vector": "vector_cosine_ops"},
    )
    op.drop_index(
        op.f("ix_messages_embedding_vector_l2"),
        table_name="messages",
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.create_index(
        "ix_messages_embedding_vector_l2",
        "messages",
        ["embedding"],
        unique=False,
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"embedding_vector": "vector_l2_ops"},
    )
    op.drop_column("messages", "embedding_vector")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "embedding_vector",
            pgvector.sqlalchemy.vector.VECTOR(dim=768),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(
        "ix_messages_embedding_vector_l2",
        table_name="messages",
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"embedding_vector": "vector_l2_ops"},
    )
    op.create_index(
        op.f("ix_messages_embedding_vector_l2"),
        "messages",
        ["embedding_vector"],
        unique=False,
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.drop_index(
        "ix_messages_embedding_vector_cosine",
        table_name="messages",
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"embedding_vector": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_messages_embedding_vector_cosine"),
        "messages",
        ["embedding_vector"],
        unique=False,
        postgresql_ops={"embedding_vector": "vector_cosine_ops"},
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.drop_column("messages", "embedding")
    # ### end Alembic commands ###
