"""Make agentfield nullable

Revision ID: e6d11e3541ad
Revises: fa706af4dfdf
Create Date: 2025-09-19 14:16:21.156757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d11e3541ad'
down_revision: Union[str, Sequence[str], None] = 'fa706af4dfdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'agent_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'agent_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
