"""add cascade delete

Revision ID: fa706af4dfdf
Revises: 5fcde2f1df52
Create Date: 2025-09-16 15:21:09.871604

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa706af4dfdf"
down_revision: str | Sequence[str] | None = "5fcde2f1df52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_agents_guild_id_guilds"), "agents", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_agents_guild_id_guilds"),
        "agents",
        "guilds",
        ["guild_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_channels_guild_id_guilds"), "channels", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_channels_guild_id_guilds"),
        "channels",
        "guilds",
        ["guild_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_messages_user_id_users"), "messages", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_messages_channel_id_channels"), "messages", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_messages_user_id_users"),
        "messages",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_messages_channel_id_channels"),
        "messages",
        "channels",
        ["channel_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_messages_channel_id_channels"), "messages", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_messages_user_id_users"), "messages", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_messages_channel_id_channels"),
        "messages",
        "channels",
        ["channel_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_messages_user_id_users"), "messages", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_channels_guild_id_guilds"), "channels", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_channels_guild_id_guilds"), "channels", "guilds", ["guild_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_agents_guild_id_guilds"), "agents", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_agents_guild_id_guilds"), "agents", "guilds", ["guild_id"], ["id"]
    )
    # ### end Alembic commands ###
